server:
  port: 8443
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-store-password: dmswns
    key-store-type: PKCS12
spring:
  datasource:
    hikari:
      connection-timeout: 5000
      idleTimeout: 40000
      maxLifetime: 580000
      validation-timeout: 10000
    password: quant14
    url: jdbc:postgresql://rion5.kro.kr:8080/quantdb
    username: quant