server:
  port: 8443
  ssl:                                        #개발환경에서는 http 사용
      key-store: classpath:ssl/keystore.p12     #개발환경에서는 http 사용
      key-store-password: dmswns                #개발환경에서는 http 사용
      key-store-type: PKCS12                    #개발환경에서는 http 사용
spring:
  datasource:
    hikari:
      connection-timeout: 5000
      idleTimeout: 40000
      maxLifetime: 580000
      validation-timeout: 10000
    password: quant14
    url: jdbc:postgresql://localhost:8080/quantdb  #개발환경 localhost:8080 사용 / 운영환경 rion5.kro.kr:8080
    username: quant