server:
  port: 8443
  ssl:
    key-store: classpath:ssl/rion5.kro.kr.p12
    key-store-password: altpajswl
    key-store-type: PKCS12
spring:
  datasource:
    hikari:
      connection-timeout: 5000
      idleTimeout: 40000
      maxLifetime: 580000
      validation-timeout: 10000
    password: quant14
    url: jdbc:postgresql://localhost:5432/quantdb
    username: quant