server:
  port: 8443
  ssl:                                        
      key-store:                          
      key-store-password:                 
      key-store-type:                     
spring:
  datasource:
    hikari:
      connection-timeout: 5000
      idleTimeout: 40000
      maxLifetime: 580000
      validation-timeout: 10000
    password: samplepw
    url: jdbc:postgresql://localhost:8080/sampledb
    username: sample